port: 8109

title:            'Bloggy'
tagline:          'Blog post ideas, for free.'
description:      ''
url:              
baseurl:          ''

gems:
  - jekyll-feed
  - jekyll-sitemap # leave at the end
  
collections:
    ideas:
        output: false