port: 8109

title:            'Blog Post Ideas'
tagline:          'Blog post ideas, for free.'
description:      ''
url:              
baseurl:          '/blog-post-ideas'

gems:
  - jekyll-feed
  - jekyll-sitemap # leave at the end

collections:
  ideas:
    output: true

defaults:
  - scope:
      path: ""
      type: ideas
    values:
      layout: idea